/* @flow */

export const REDUX_TYPE_SET_LANGUAGE: 'REDUX_TYPE_SET_LANGUAGE' = 'REDUX_TYPE_SET_LANGUAGE';
export const REDUX_TYPE_SPLASH_SCREEN_SHOWN: 'REDUX_TYPE_SPLASH_SCREEN_SHOWN' = 'REDUX_TYPE_SPLASH_SCREEN_SHOWN';
